/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package android.forensic.toolkit;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.filechooser.FileSystemView;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author Resley Rodrigues
 */
public class MainJFrame extends javax.swing.JFrame {

    public void getDrives() {

        DriveSelector.removeAllItems();
        File[] roots = File.listRoots();
        for (int i = 0; i < roots.length; i++) {
            DriveSelector.addItem(roots[i]);
        }
        jTabbedPane1.setTitleAt(0, "Boot Sector");
        jTabbedPane1.setTitleAt(1, "FAT");
 //       jTabbedPane1.setTitleAt(2, "Boot Sector HEX View");
    }

    void addNode(DefaultMutableTreeNode top, String path) {
        File temp = new File(path);
        File[] children = temp.listFiles();
        DefaultMutableTreeNode node;
        for (File c : children) {
            if (c.isHidden()) {
                node = new DefaultMutableTreeNode(c.getName() + "   -hidden");
            } else {
                node = new DefaultMutableTreeNode(c.getName());
            }
            if (c.isDirectory()) {
                addNode(node, c.getAbsolutePath());
            }
            top.add(node);
            System.out.println(c.getName());
        }
    }

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cloneDialog = new javax.swing.JDialog();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jButton5 = new javax.swing.JButton();
        hashDialog = new javax.swing.JDialog();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        DriveSelector = new javax.swing.JComboBox();
        lbl_SelectDrive = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        VolumeLabel = new javax.swing.JLabel();
        FreeSpace = new javax.swing.JLabel();
        TotalSpace = new javax.swing.JLabel();
        DriveType = new javax.swing.JLabel();
        lbl_Label = new javax.swing.JLabel();
        lbl_FreeSpace = new javax.swing.JLabel();
        lbl_TotalSize = new javax.swing.JLabel();
        lbl_Type = new javax.swing.JLabel();
        FileList = new javax.swing.JScrollPane();
        FileListTree = new javax.swing.JTree();
        jTextField1 = new javax.swing.JTextField();
        RefreshDriveList = new javax.swing.JButton();
        lbl_Hash = new javax.swing.JLabel();
        Hash = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        BootSector = new javax.swing.JScrollPane();
        BootSectorData = new javax.swing.JTextArea();
        BootSectorHex = new javax.swing.JScrollPane();
        BootSectorHexData = new javax.swing.JTextArea();
        PartitionTable = new javax.swing.JScrollPane();
        PartitionTableData = new javax.swing.JTextArea();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "C:\\", "D:\\", "E:\\", "F:\\" }));

            jLabel1.setText("Disk to Clone:");

            jTextField2.setText("E:\\");

                jLabel2.setText("Save to: ");

                jButton4.setText("Browse");

                jProgressBar1.setValue(74);

                jButton5.setText("Cancel");
                jButton5.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton5ActionPerformed(evt);
                    }
                });

                javax.swing.GroupLayout cloneDialogLayout = new javax.swing.GroupLayout(cloneDialog.getContentPane());
                cloneDialog.getContentPane().setLayout(cloneDialogLayout);
                cloneDialogLayout.setHorizontalGroup(
                    cloneDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cloneDialogLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(cloneDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(cloneDialogLayout.createSequentialGroup()
                                .addGroup(cloneDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cloneDialogLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField2))
                                    .addGroup(cloneDialogLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(51, 51, 51)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(cloneDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(26, Short.MAX_VALUE))
                );
                cloneDialogLayout.setVerticalGroup(
                    cloneDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cloneDialogLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(cloneDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jButton5))
                        .addGap(18, 18, 18)
                        .addGroup(cloneDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jButton4))
                        .addGap(18, 18, 18)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))
                );

                jRadioButton1.setText("MD5");
                jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jRadioButton1ActionPerformed(evt);
                    }
                });

                jRadioButton2.setText("SHA1");

                jRadioButton3.setText("SHA2");

                jLabel3.setText("Choose Algorithm:");

                jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "C:\\", "D:\\", "E:\\", "F:\\" }));

                    jTextField3.setText("D:\\HashRecords\\DriveF.txt");

                    jLabel4.setText("Compare With:");

                    jLabel5.setText("Disk to Hash:");

                    jButton6.setText("Cancel");
                    jButton6.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            jButton6ActionPerformed(evt);
                        }
                    });

                    jButton7.setText("Browse");

                    jLabel6.setText("Hash Value:");

                    jTextField4.setText("3DA3828BAC4918CAED8AA82F71");

                    jButton8.setText("Compute");
                    jButton8.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            jButton8ActionPerformed(evt);
                        }
                    });

                    javax.swing.GroupLayout hashDialogLayout = new javax.swing.GroupLayout(hashDialog.getContentPane());
                    hashDialog.getContentPane().setLayout(hashDialogLayout);
                    hashDialogLayout.setHorizontalGroup(
                        hashDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(hashDialogLayout.createSequentialGroup()
                            .addGroup(hashDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(hashDialogLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(hashDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(hashDialogLayout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(18, 18, 18)
                                            .addComponent(jRadioButton1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jRadioButton2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jRadioButton3))
                                        .addGroup(hashDialogLayout.createSequentialGroup()
                                            .addGroup(hashDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, hashDialogLayout.createSequentialGroup()
                                                    .addComponent(jLabel5)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, hashDialogLayout.createSequentialGroup()
                                                    .addGroup(hashDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel6))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addGroup(hashDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(hashDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jButton8)
                                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(hashDialogLayout.createSequentialGroup()
                                    .addGap(136, 136, 136)
                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    );
                    hashDialogLayout.setVerticalGroup(
                        hashDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(hashDialogLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(hashDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButton1)
                                .addComponent(jRadioButton2)
                                .addComponent(jRadioButton3)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(hashDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addComponent(jButton8))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(hashDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(11, 11, 11)
                            .addGroup(hashDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(jButton7))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                            .addComponent(jButton6)
                            .addContainerGap())
                    );

                    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                    setTitle("Android Forensic Toolkit");
                    setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

                    DriveSelector.setName(""); // NOI18N

                    lbl_SelectDrive.setText("Select Drive");

                    jButton1.setText("Get Details");
                    jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            jButton1ActionPerformed(evt);
                        }
                    });

                    VolumeLabel.setText("vol_lbl");
                    VolumeLabel.setToolTipText("");

                    FreeSpace.setText("free");

                    TotalSpace.setText("total");

                    DriveType.setText("jLabel6");

                    lbl_Label.setText("Label:");

                    lbl_FreeSpace.setText("Free Space:");

                    lbl_TotalSize.setText("Total Size:");

                    lbl_Type.setText("Type:");

                    javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
                    FileListTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
                    FileListTree.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                            FileListTreeMouseClicked(evt);
                        }
                    });
                    FileList.setViewportView(FileListTree);

                    jTextField1.setText("jTextField1");

                    RefreshDriveList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/android/forensic/toolkit/refresh.png"))); // NOI18N
                    RefreshDriveList.setToolTipText("Refresh");
                    RefreshDriveList.setBorder(null);
                    RefreshDriveList.setBorderPainted(false);
                    RefreshDriveList.setContentAreaFilled(false);
                    RefreshDriveList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                    RefreshDriveList.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            RefreshDriveListActionPerformed(evt);
                        }
                    });

                    lbl_Hash.setText("Hash Values");

                    jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                    jTabbedPane1.setName(""); // NOI18N

                    BootSectorData.setColumns(20);
                    BootSectorData.setRows(5);
                    BootSector.setViewportView(BootSectorData);

                    jSplitPane1.setLeftComponent(BootSector);

                    BootSectorHexData.setColumns(20);
                    BootSectorHexData.setRows(5);
                    BootSectorHex.setViewportView(BootSectorHexData);

                    jSplitPane1.setRightComponent(BootSectorHex);

                    jTabbedPane1.addTab("BootSector", jSplitPane1);

                    PartitionTableData.setColumns(20);
                    PartitionTableData.setRows(5);
                    PartitionTable.setViewportView(PartitionTableData);

                    jTabbedPane1.addTab("FAT", PartitionTable);

                    jInternalFrame1.setVisible(true);

                    javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
                    jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
                    jInternalFrame1Layout.setHorizontalGroup(
                        jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 962, Short.MAX_VALUE)
                    );
                    jInternalFrame1Layout.setVerticalGroup(
                        jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 195, Short.MAX_VALUE)
                    );

                    jTabbedPane1.addTab("tab3", jInternalFrame1);

                    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                    jPanel1.setLayout(jPanel1Layout);
                    jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 978, Short.MAX_VALUE)
                    );
                    jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 225, Short.MAX_VALUE)
                    );

                    jTabbedPane1.addTab("tab4", jPanel1);

                    jButton2.setText("Clone Disk");
                    jButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            jButton2ActionPerformed(evt);
                        }
                    });

                    jButton3.setText("Compute Hash");
                    jButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            jButton3ActionPerformed(evt);
                        }
                    });

                    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                    getContentPane().setLayout(layout);
                    layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(FileList)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_SelectDrive)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(DriveSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_Label)
                                        .addComponent(lbl_Type)
                                        .addComponent(lbl_FreeSpace)
                                        .addComponent(lbl_TotalSize))
                                    .addGap(9, 9, 9)
                                    .addComponent(RefreshDriveList, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TotalSpace)
                                        .addComponent(FreeSpace)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(VolumeLabel)
                                                .addComponent(DriveType)
                                                .addComponent(jButton1))
                                            .addGap(87, 87, 87)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jButton2)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jButton3))
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(lbl_Hash)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(Hash)))))))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    );
                    layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(lbl_SelectDrive)
                            .addGap(1, 1, 1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1)
                                    .addComponent(jButton2)
                                    .addComponent(jButton3))
                                .addComponent(RefreshDriveList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DriveSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbl_Label)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_Type)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbl_FreeSpace)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbl_TotalSize, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(VolumeLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(DriveType)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(FreeSpace)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TotalSpace))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_Hash)
                                        .addComponent(Hash))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(FileList, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                    );

                    VolumeLabel.getAccessibleContext().setAccessibleName("VolumeLabel");
                    DriveType.getAccessibleContext().setAccessibleName("");

                    pack();
                }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String path, freeSpace, totalSpace;
        path = DriveSelector.getSelectedItem().toString();
        File temp = new File(path);

        freeSpace = Utils.getSize(temp.getFreeSpace());
        totalSpace = Utils.getSize(temp.getTotalSpace());

               VolumeLabel.setText(FileSystemView.getFileSystemView().getSystemDisplayName(temp));
        DriveType.setText(FileSystemView.getFileSystemView().getSystemTypeDescription(temp));
        FreeSpace.setText(freeSpace);
//        TotalSpace.setText(totalSpace);
        FileListTree.removeAll();
        FileListTree.repaint();

//
//        DefaultMutableTreeNode top = new DefaultMutableTreeNode(path);
//
//               addNode(top,path);
//         FileListTree.setModel(new DefaultTreeModel(top));
//         FileListTree.repaint();
         File diskRoot = new File("\\\\.\\" + path);
        RandomAccessFile diskAccess;
        try {
            MessageDigest md = MessageDigest.getInstance("MD5");
            diskAccess = new RandomAccessFile(diskRoot, "r");
            byte[] content = new byte[1024];
            diskAccess.readFully(content);
            md.update(content);
            Hash.setText(Utils.byteToHex(md.digest()));
            String temp_str = "";
            for (int i = 71; i <= 81; i++) {
                temp_str = temp_str.concat(String.valueOf(Utils.hexToText(Utils.hex(content[i]))));
            }
        //    VolumeLabel.setText(temp_str);

            BootSectorData.setText("");
            PartitionTableData.setText("");
            BootSectorHexData.setText("");
            BootSectorData.setTabSize(3);
            PartitionTableData.setTabSize(3);
            BootSectorHexData.setTabSize(3);
            String jump_instruction = Utils.hex(content[0]) + Utils.hex(content[1]) + Utils.hex(content[2]);
            int txm;
            switch (jump_instruction) {
                case "EB5290":
                    {
                        NTFS disk = new NTFS();
                        jTabbedPane1.setTitleAt(1, "MFT");
                        disk.getBPB(path);
                        disk.printBPB(BootSectorData,BootSectorHexData);
                        disk.readMFT(PartitionTableData);
                        TotalSpace.setText(Utils.getSize(disk.bytes_per_Sector * disk.total_sectors));
                        break;
                    }
                case "EB5890":
                    {
                        FAT32 disk = new FAT32();
                        jTabbedPane1.setTitleAt(1, "FAT");
                        disk.getBPB(path);
                        disk.printBPB(BootSectorData,BootSectorHexData);
                        disk.readFAT(PartitionTableData);
                        VolumeLabel.setText(disk.label);
                        jTextField1.setText(disk.type);
                        if(disk.total_sectors==0)
                            TotalSpace.setText(Utils.getSize(disk.bytes_per_Sector*disk.total_sectorsL));
                        else
                            TotalSpace.setText(Utils.getSize(disk.bytes_per_Sector*disk.total_sectors));
                        break;
                    }
                default:
                    int sector_size = Utils.hexToInt(Utils.hex(content[11]), Utils.hex(content[12]));
                    int reserved_sectors = Utils.hexToInt(Utils.hex(content[14]), Utils.hex(content[15]));
                    int number_of_fat_sectors = Utils.hexToInt(Utils.hex(content[36]), Utils.hex(content[37]), Utils.hex(content[38]), Utils.hex(content[39]));
                    BootSectorData.append("OEM = ");
                    for (int i = 3; i <= 10; i++) {
                        BootSectorData.append(String.valueOf(Utils.hexToText(Utils.hex(content[i]))));
                    }
                    BootSectorData.append("\nFilesystem Type = ");
                    for (int i = 82; i <= 89; i++) {
                        BootSectorData.append(String.valueOf(Utils.hexToText(Utils.hex(content[i]))));
                    }
                    BootSectorData.append("\nNumber of bytes per sector = " + sector_size + "\n");
                    BootSectorData.append("Number of sectors per cluster = " + Utils.hexToInt(Utils.hex(content[13]), "00") + "\n");
                    BootSectorData.append("Number of reserved sectors = " + reserved_sectors + "\n");
                    BootSectorData.append("Number of sectors in filesystem = " + Utils.hexToInt(Utils.hex(content[19]), Utils.hex(content[20])) + "\n");
                    BootSectorData.append("Number of sectors per FAT = " + number_of_fat_sectors + "\n");
                    BootSectorData.append("\t\t 0\t 1\t 2\t 3\t 4\t 5\t 6\t 7\t\t 8\t 9\t A\t B\t C\t D\t E\t F");
                    PartitionTableData.append("\t\t 0\t 1\t 2\t 3\t 4\t 5\t 6\t 7\t\t 8\t 9\t A\t B\t C\t D\t E\t F");
                    int address = 0x000000;
                    for (int i = 0; i < sector_size; i++) {
                        txm = content[i];
                        if (i % 16 == 0) {
                            BootSectorData.append(String.format("\n%07X0\t", address++));
                        } else if (i % 8 == 0) {
                            BootSectorData.append("\t");
                        }
                        BootSectorData.append(Utils.hex(txm) + "\t");
                    }
                    //   System.out.println("Disk size = "+ getSize(diskAccess.length()));
                    System.out.println("File pointer at " + diskAccess.getFilePointer());
                    diskAccess.seek(reserved_sectors * sector_size);
                    System.out.println("File pointer at " + diskAccess.getFilePointer());
                    content = new byte[sector_size * number_of_fat_sectors];
                    System.out.println("index=" + reserved_sectors * sector_size);
                    System.out.println("len = " + sector_size * 2);
                    diskAccess.read(content, 0, sector_size * number_of_fat_sectors);
                    System.out.println("works");
                    //        address = Integer.valueOf(Integer.toHexString(reserved_sectors*sector_size), 16);
                    address = Integer.parseInt(Integer.toHexString(reserved_sectors * sector_size), 16);
                    System.out.println("Address = " + address);
                    for (int i = 0; i < 1921024; i++) {
                        txm = content[i];
                        if (i % 16 == 0) {
                            PartitionTableData.append(String.format("\n%08X\t", address));
                            System.out.println(String.format("@ %08X",address));
                            address += 16;
                        } else if (i % 8 == 0) {
                            PartitionTableData.append("\t");
                        }
                        PartitionTableData.append(Utils.hex(txm) + "\t");

                    }
                    diskAccess.seek(4308992);  //root directory for my pendrive
                    content = new byte[16384];
                    System.out.println("@" + diskAccess.getFilePointer());
                    diskAccess.readFully(content);
                    for (int i = 0; i < 512; i++) {

                        for (int j = (i * 32); j <= (i * 32) + 10; j++) {
                            System.out.print(Utils.hexToText(Utils.hex(content[j])));
                        }
                        System.out.print("    ");
                        System.out.print((Utils.hex(content[(i * 32) + 11])));
                        System.out.print("    ");
                        int temp_int = 0;
                        for (int j = (i * 32) + 27; j < (i * 32) + 32; j++) {
                            temp_int += Utils.hexToInt(Utils.hex(content[j]), "00");
                        }
                        System.out.print(Utils.getSize(temp_int));
                        System.out.println();
                    }
                    break;
            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException | NoSuchAlgorithmException ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RefreshDriveListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshDriveListActionPerformed
        this.getDrives();
    }//GEN-LAST:event_RefreshDriveListActionPerformed

    private void FileListTreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FileListTreeMouseClicked
        System.out.println(FileListTree.getLastSelectedPathComponent().toString().replace(',', '\\'));
    }//GEN-LAST:event_FileListTreeMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cloneDialog.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
hashDialog.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainJFrame a = new MainJFrame();
                a.setVisible(true);
                a.getDrives();

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane BootSector;
    private javax.swing.JTextArea BootSectorData;
    private javax.swing.JScrollPane BootSectorHex;
    private javax.swing.JTextArea BootSectorHexData;
    private javax.swing.JComboBox DriveSelector;
    private javax.swing.JLabel DriveType;
    private javax.swing.JScrollPane FileList;
    private javax.swing.JTree FileListTree;
    private javax.swing.JLabel FreeSpace;
    private javax.swing.JLabel Hash;
    private javax.swing.JScrollPane PartitionTable;
    private javax.swing.JTextArea PartitionTableData;
    private javax.swing.JButton RefreshDriveList;
    private javax.swing.JLabel TotalSpace;
    private javax.swing.JLabel VolumeLabel;
    private javax.swing.JDialog cloneDialog;
    private javax.swing.JDialog hashDialog;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lbl_FreeSpace;
    private javax.swing.JLabel lbl_Hash;
    private javax.swing.JLabel lbl_Label;
    private javax.swing.JLabel lbl_SelectDrive;
    private javax.swing.JLabel lbl_TotalSize;
    private javax.swing.JLabel lbl_Type;
    // End of variables declaration//GEN-END:variables
}
